CREATE DATABASE board;

USE board;

CREATE TABLE BOARD_INPO
(
	BOARD_NO	INT AUTO_INCREMENT PRIMARY KEY
	,BOARD_TITLE VARCHAR(100) NOT NULL
	,BOARD_CONTENTS VARCHAR(1000) NOT NULL
	,BOARD_WRITE_DATE	DATETIME	NOT NULL
	,BOARD_DEL_FLG	CHAR(1) NOT NULL DEFAULT ('0')
	,BOARD_DLE_DATE DATETIME
);

-- ALTER TABLE BOARD_IMPO 
-- 	ADD CONSTRAINT PK_BOARD_IMPO 
-- 	PRIMARY KEY (BOARD_NO);
	
-- DROP TABLE board_impo;

DESC board_inpo;

INSERT INTO BOARD_INPO
(
	BOARD_TITLE
	,BOARD_CONTENTS
	,BOARD_WRITE_DATE
)
VALUES  
(
	"제목20"
	,"내용20"
	,NOW()
);

COMMIT;

