

CREATE TABLE TEST_STUDENT(
	STU_NO INT(10) NOT NULL
	,STU_BIRTH DATE NOT NULL
	,STU_NAME VARCHAR(30) NOT NULL
	,STU_ADDR VARCHAR(100) NOT NULL
	,STU_TEL VARCHAR(11) NOT NULL
	,STU_GENDER CHAR(1) NOT NULL
	,STU_ADMIS DATE NOT NULL
	,STU_GRADUA DATE NOT NULL
	,STU_STATUS ENUM('Y','N') NOT NULL
	,CONSTRAINT PK_TEST_STUDENT_STU_NO PRIMARY KEY(STU_NO)
);
-- 프라이머리키만 이름설정 불가 MARIA DB에서만
-- ALTER TABLE TEST_STUDENT ALTER COLUMN STU_TEL CHAR(11);
-- ALTER TABLE TEST_STUDENT DROP COLUMN STU_TEL;


-- CREATE TABLE TEST_STUDENT(
--	STU_NO INT(10) PRIMARY KEY
--	,STU_BIRTH DATE NOT NULL
--	,STU_NAME VARCHAR(30) NOT NULL
--	,STU_ADDR VARCHAR(100) NOT NULL
--	,STU_TEL CHAR(11) NOT NULL
--	,STU_GENDER CHAR(1) NOT NULL
--	,STU_ADMIS DATE NOT NULL
--	,STU_GRADUA DATE NULL
--	,STU_STATUS ENUM('Y','N') NOT NULL
--	,CONSTRAINT PK_TEST_STUDENT_STU_NO PRIMARY KEY(STU_NO)
-- );

CREATE TABLE TEST_PROFESSOR(
	PROF_NO INT(10) NOT NULL
	,PROF_NAME VARCHAR(30) NOT NULL
	,PROF_BIRTH DATE NOT NULL
	,PROF_DEGREENU INT(10) NOT NULL
	,PROF_EMAIL VARCHAR(100) NOT NULL UNIQUE
	,PROF_TITLE VARCHAR(30) NOT NULL
	,PROF_LABNO INT(10) NOT NULL
	,PROF_GENDER CHAR(1) NOT NULL
	,PROF_HIREDATE DATE NOT NULL
	,CONSTRAINT PK_TEST_PROFESSOR_PROF_NO PRIMARY KEY(PROF_NO)
);

CREATE TABLE TEST_TEXTBOOK (
	TEXTB_NO INT(10) NOT NULL
	,TEXTB_NAME VARCHAR(50) NOT NULL
	,CONSTRAINT PK_TEST_TEXTBOOK_TEXTB_NO PRIMARY KEY(TEXTB_NO)
);

CREATE TABLE TEST_SUBJECT(
	SUBJ_NO INT(10) NOT NULL
	,SUBJ_NAME VARCHAR(100) NOT NULL
	,SUBJ_CAPACITY INT(2) NOT NULL
	,SUBJ_CLASSTERM INT(10) NOT NULL
	,SUBJ_CLASSNO INT(10) NOT NULL
	,SUBJ_STARTTIME TIME NOT NULL
	,SUBJ_ENDTTIME TIME NOT NULL
	,TEXTB_NO INT(10) NOT NULL
	,SUBJ_REQUIRED INT(10) NOT NULL
	,PROF_NO INT(10) NOT NULL
	,CONSTRAINT PK_TEST_SUBJECT_SUBJ_NO PRIMARY KEY(SUBJ_NO)
);

CREATE TABLE TEST_GRADE(
	STU_NO INT(10) NOT NULL
	,SUBJ_NO INT(10) NOT NULL
	,GRA_GRADE INT(1) NOT NULL
	,GRA_RANK INT(1) NOT NULL
	,GRA_DATE DATE NOT NULL
	,CONSTRAINT PK_TEST_GRADE_STU_SUBJ_NO PRIMARY KEY(STU_NO,SUBJ_NO)
);

-- CREATE TABLE TEST_GRADE(
--	STU_NO INT(10)
--	,SUBJ_NO INT(10) NOT NULL
--	,GRA_SCORE INT(1) NOT NULL
--	,GRA_RANK INT(1) NOT NULL
--	,GRA_DATE DATE NOT NULL
--	,PRIMARY KEY(STU_NO,SUBJ_NO)
-- );


ALTER TABLE test_grade
ADD
FOREIGN KEY (STU_NO)
REFERENCES TEST_STUDENT (STU_NO);

ALTER TABLE TEST_SUBJECT
ADD
FOREIGN KEY (PROF_NO)
REFERENCES TEST_PROFESSOR (PROF_NO);

ALTER TABLE TEST_SUBJECT
ADD
FOREIGN KEY (TEXTB_NO)
REFERENCES TEST_TEXTBOOK (TEXTB_NO);

ALTER TABLE TEST_GRADE
ADD
FOREIGN KEY (SUBJ_NO)
REFERENCES TEST_SUBJECT (SUBJ_NO);







