-- 노랑 PK

CREATE TABLE TEST_EMPLOYEES(
	EMP_NO INT(11)
	,BIRTH_DATE DATE
	,FIRST_NAME VARCHAR(14)test_titles
	,LAST_NAME VARCHAR(16)
	,GENDER ENUM('M','F')
	,HIRE_DATE DATE
	,CONSTRAINT PK_TEST_EMPLOYEES_EMP_NO PRIMARY KEY(EMP_NO)
);

CREATE TABLE TEST_SALARIES(
	EMP_NO INT(11)
	,SALARY INT(11)
	,FROM_DATE DATE
	,TO_DATE DATE
	,CONSTRAINT PK_TEST_SALARIES_EMP_FROM PRIMARY KEY(EMP_NO,FROM_DATE)
);



CREATE TABLE TEST_TITLES(
	EMP_NO INT(11)
	,TITLE VARCHAR(50)
	,FROM_DATE DATE
	,TO_DATE DATE
	,CONSTRAINT PK_TEST_TITLES_EMP_TITLE_FROM PRIMARY KEY(EMP_NO,TITLE,FROM_DATE)
);


-- 인덱스: 검색성능, 검색속도를 높이기 위한것
CREATE INDEX T_SAL_EMP_NO ON TEST_SALARIES(EMP_NO);
CREATE INDEX T_TIT_EMP_NO  ON TEST_TITLES(EMP_NO);
CREATE INDEX T_D_EM_EMP_DEPT_NO  ON TEST_DEPT_EMP(EMP_NO,DEPT_NO);
CREATE INDEX T_DEPA_DEPT_NAME  ON TEST_DEPARTMENTS(DEPT_NAME);
CREATE INDEX T_D_MA_EMP_DEPT_NO  ON TEST_DEPT_MANAGER(EMP_NO,DEPT_NO);

CREATE TABLE TEST_DEPT_EMP(
	EMP_NO INT(11)
	,DEPT_NO CHAR(4)
	,FROM_DATE DATE
	,TO_DATE DATE
	,CONSTRAINT PK_TEST_DEPT_EMP_EMP_DEPT PRIMARY KEY(EMP_NO,DEPT_NO)
);

CREATE TABLE TEST_DEPARTMENTS(
	DEPT_NO CHAR(4)
	,DEPT_NAME VARCHAR(40)
	,CONSTRAINT PK_TEST_DEPARTMENTS_DEPT_NO PRIMARY KEY(DEPT_NO)
);

CREATE TABLE TEST_DEPT_MANAGER(
	DEPT_NO CHAR(4)
	,EMP_NO INT(11)
	,FROM_DATE DATE
	,TO_DATE DATE
	,CONSTRAINT PK_TEST_DEPT_MANAGER_DEPT_EMP_NO PRIMARY KEY(DEPT_NO,EMP_NO)
);

ALTER TABLE test_salaries
ADD
FOREIGN KEY (EMP_NO)
REFERENCES test_employees (EMP_NO);

ALTER TABLE test_titles
ADD
FOREIGN KEY (EMP_NO)
REFERENCES test_employees (EMP_NO);

ALTER TABLE test_dept_emp
ADD
FOREIGN KEY (EMP_NO)
REFERENCES test_employees (EMP_NO);

ALTER TABLE test_dept_manager
ADD
FOREIGN KEY (EMP_NO)
REFERENCES test_employees (EMP_NO);

ALTER TABLE test_dept_manager
ADD
FOREIGN KEY (DEPT_NO)
REFERENCES TEST_DEPARTMENTS (DEPT_NO);

ALTER TABLE TEST_DEPT_EMP
ADD
FOREIGN KEY (DEPT_NO)
REFERENCES TEST_DEPARTMENTS (DEPT_NO);

-- 단일 인덱스
-- CREATE INDEX 인덱스이름 ON 테이블이름(필드이름1)

-- 다중 컬럼 인덱스
-- CREATE INDEX 인덱스이름 ON 테이블이름(필드이름1, 필드이름2, ...)

-- 인덱스 조회
-- SHOW INDEX FROM 테이블이름

-- UNUQUE 인덱스 생성(중복 값을 허용하지 않는 인덱스)
-- 단일 인덱스
-- CREATE UNIQUE INDEX 인덱스 이름 ON 테이블이름(필드이름1)
-- 다중 컬럼 인덱스
-- CREATE UNIQUE INDEX 인덱스 이름 ON 테이블이름(필드이름1, 필드이름2, ...)

-- ALTER 문으로 FOREIGN KEY 설정
-- ALTER TABLE 테이블이름
-- ADD [CONSTRAINT 제약조건이름]
-- FOREIGN KEY (필드이름)
-- REFERENCES 테이블이름 (필드이름)






-- ROLLBACK;
-- DROP TABLE TEST_EMPLOYEES;
-- CUMMIT;
-- COMMIT;
